import os

GROQ_API_BASE = "https://api.groq.com/openai/v1"
GROQ_CHAT_MODEL = os.environ.get("GROQ_CHAT_MODEL", "llama-3.1-8b-instant")
GROQ_CODING_MODEL = "llama-3.3-70b-versatile"
GROQ_COMPOUND_MODEL = "llama-3.3-70b-versatile"
GROQ_CHAT_API_KEY = os.environ.get("GROQ_CHAT_API_KEY", "")
GROQ_CODING_API_KEY = os.environ.get("GROQ_CHAT_API_KEY", "")
GROQ_COMPOUND_API_KEY = os.environ.get("GROQ_CHAT_API_KEY", "")
SERP_API_KEY = os.environ.get("SERP_API_KEY", "")
NEWS_API_KEY = os.environ.get("NEWS_API_KEY", "")
JARVIS_TIMEZONE = "Asia/Kolkata"
WAKE_WORD = "jarvis"
JARVIS_WEATHER_API_KEY = os.environ.get("JARVIS_WEATHER_API_KEY", "")
JARVIS_WEATHER_API_BASE = "https://api.weatherapi.com/v1"
JARVIS_WEATHER_PROVIDER = "weatherapi"
VISION_MODEL = "llama-3.2-11b-vision-preview"
HOME = os.path.expanduser("~")
NOTES_DIR = os.environ.get("JARVIS_NOTES_DIR", os.path.join(HOME, "storage", "shared", "Jarvis_Notes"))
os.makedirs(NOTES_DIR, exist_ok=True)
AUDIO_SAMPLE_RATE = 16000
AUDIO_CHANNELS = 1
AUDIO_FRAME_MS = 30
ENERGY_THRESHOLD = 1500
VAD_AGGRESSIVENESS = 3
SPEAKER_THRESHOLD = 0.75
MAX_COMMAND_DURATION = 60
SILENCE_TIMEOUT = 2.2
SPEAKER_RECHECK_INTERVAL = 1.0
TASK_CHAIN_KEYWORDS = ["then", "after that", "and then", "also", "and also", "next"]
MAX_TASKS_IN_CHAIN = 5
